# This file defines the principal settings for this project

REPO_NAME          := iron-horse

BASE_FILENAME      := iron-horse

# Documentation files:
DOC_FILES = docs/license.txt docs/changelog.txt

# If you want to use gimp to automatically create the png files from
# layered source files (psd or xcf), uncomment the following line and
# create the file and add one line per png file which shall be created:
# png filename <tab> source filename <tab> layer numbers separated by space
# (see also scripts/gimpscript)
# GRAPHICS_SOURCE_LIST_FILES := gfx/png_source_list

# If everything is default, you don't need the rest:
# EXTRA_DEP          :=

SCRIPT_DIR         := scripts

# Files which also need cleaning:
CLEAN_ADD             := docs/readme.txt docs/set_overview.html

NML_FLAGS      := -c -l generated/lang
