from roster import Roster

# list in buy menu order
engine_module_names = [
    # branch express
    "lark",
    "merrylegs",
    "decapod",
    "proper_job",
    "stag",
    "kelpie",
    "foxhound",
    "griffon",
    "wildfire",
    "pinhorse",
    "argus",
    "booster",
    "tornado",
    # express
    "reliance",
    "spinner",
    "carrack",
    "braf",
    "tencendur",
    "diablo",
    "satyr",
    "thunderer",
    "daring",
    "growler",
    "merlion",
    "shredder",
    "phoenix",
    "centaur",
    "swift",
    "strongbow",
    "arrow",
    "wyvern",
    "tenacious",
    "intrepid",
    "resilient",
    "rapid",
    "pegasus",
    "streamer",
    "hawkinge",
    "dragon",
    "vulcan",
    "falcon",
    "onslaught",
    "dreadnought",
    "defiant",
    "relentless",
    "dynamo",
    "cyclone",
    "shoebox",
    "ultra_shoebox",
    "hurly_burly",
    "moor_gallop",
    "roarer",
    "fury",
    "constance",
    "stalwart",
    "zebedee",
    "screamer",
    "revolution",
    "avenger",
    "sizzler",
    # branch freight
    "buffalo",
    "pika",
    "ox",
    "saxon",
    "yak",
    "little_bear",
    "captain_steel",
    "rat",
    "goliath",
    "general_endeavour",
    "lynx",
    "stoat",
    "zest",
    # freight
    "hercules",
    "eastern",
    "abernant",
    "haar",
    "trojan",
    "smizzle",
    "viking",
    "westrail",
    "xerxes",
    "keen",
    "vigilant",
    "mainstay",
    "yillen",
    "maelstrom",
    "doineann",
    "doubletide",
    "girt_licker",
    "lemon",
    "esk",
    "backbone",
    "chinook",
    "withershins",
    "highlander",
    "grid",
    "bone",
    "lion",
    "grillage",
    "toaster",
    "cheddar_valley",
    "stentor",
    "flindermouse",
    "dryth",
    "peasweep",
    "resistance",
    "tincans",
    "flanders_storm",
    "quietus",
    # gronks / snowploughs
    "grub",
    "lamia",
    "fireball",
    "gronk",
    "chuggypig",
    "progress",
    "magnum_90",
    "snowplough_pony_gen_2",
    # cargo sprinter
    "cargo_sprinter",
    # auto-coach (only one as autoreplace can't handle mixed cargo articulated vehicles)
    "auto_coach_pony_gen_2",
    # railbuses
    "clipper",
    "skipper",
    "zipper",
    # diesel railcars
    "deasil",
    "slammer",
    "tin_rocket",
    "happy_train",
    "gowsty",
    "scooby",
    "plastic_postbox",
    # electric railcars
    "athena",
    "geronimo",
    "breeze",
    "zeus",
    "ares",
    "dover",
    "jupiter",
    "pylon",
    # express diesel railcars
    "kraken",
    "turbulent",
    "typhoon",
    # express electric railcars
    "high_flyer",
    "sunshine_coast",
    "olympic",
    "chronos",
    "nimbus",
    # brit high speed pax
    "firebird_cab",
    "blaze_cab",
    "helm_wind_cab",
    "helm_wind_middle",
    "alize_cab",
    "alize_middle",
    "brenner_cab",
    "brenner_middle",
    "skeiron_cab",
    "skeiron_middle",
    # driving cab cars
    "driving_cab_passenger_pony_gen_4",
    "driving_cab_passenger_pony_gen_5",
    "driving_cab_high_speed_passenger_pony_gen_5",
    "driving_cab_high_speed_passenger_pony_gen_6",
    "driving_cab_mail_pony_gen_5",
    "driving_cab_high_speed_mail_pony_gen_5",
    "driving_cab_high_speed_mail_pony_gen_6",
    # metro
    "serpentine",
    "poplar",
    "westbourne",
    "hammersmith",
    "fleet",
    "canary",
    "longwater",
    "ravensbourne",
    "tyburn",
    "wandle",
    "tideway",
    "bankside",
    "debden",
    "cringle",
    "mulberry",
    "walbrook",
    "borax",
    "angerstein",
    # ng engines
    "cheese_bug",
    "bean_feast",
    "pikel",
    "boar_cat",
    "thor",
    "alfama",
    "gargouille",
    "solano",
    "lebeche",
    "tyrconnell",
    "nile",
    "hinterland",
    "rockhampton",
    "higuma",
    # ng railcars
    "mumble",
    "snapper",
    "zorro",
    "ruby",
    "golfinho",
    "stratos",
    "driving_cab_passenger_ng_pony_gen_4",
    "driving_cab_panoramic_passenger_ng_pony_gen_4",
]

# these can delegate to another module for reuse of wagons; this is not a common case, but used for things like torpedo cars
# explicit wagon module lists per roster are better;
# implicit modules lists were tried (just using global_constants list and allowing failing imports), but was no less maintenance, and was faff
wagon_module_names_with_roster_ids = {
    # any engine-specific wagons go first
    "blaze_middle_cars": "pony",
    "firebird_middle_cars": "pony",
    # generic wagons
    # these can be alphabetised, the buy menu order is enforced in global constants
    "acid_tank_cars_randomised": "pony",
    "acid_tank_cars_type_1": "pony",
    "acid_tank_cars_type_2": "pony",
    "aggregate_bulk_open_cars_type_1": "pony",
    "aggregate_bulk_open_cars_type_2": "pony",
    "aggregate_bulk_open_cars_type_3": "pony",
    "aggregate_bulk_open_cars_randomised": "pony",
    "aggregate_hopper_cars_randomised": "pony",
    "aggregate_hopper_cars_type_1": "pony",
    "aggregate_hopper_cars_type_2": "pony",
    "aggregate_hopper_cars_type_3": "pony",
    "automobile_cars": "pony",
    "bolster_cars": "pony",
    "bulk_cargo_box_combos": "pony",
    "box_cars_randomised": "pony",
    "box_cars_type_1": "pony",
    "box_cars_type_2": "pony",
    "box_cars_type_3": "pony",
    "bulk_cargo_mixed_combos": "pony",
    "caboose_cars_type_1": "pony",
    "caboose_cars_type_2": "pony",
    "caboose_cars_type_3": "pony",
    "caboose_cars_type_4": "pony",
    "caboose_cars_randomised": "pony",
    "cane_bin_cars": "pony",
    "carbon_black_hopper_cars": "pony",
    "cement_silo_cars_randomised": "pony",
    "cement_silo_cars_type_1": "pony",
    "cement_silo_cars_type_2": "pony",
    "cement_silo_cars_type_3": "pony",
    "chemical_covered_hopper_cars": "pony",
    "chemical_covered_hopper_cars_randomised": "pony",
    "chemical_swing_roof_hopper_cars": "pony",
    "chemical_cargo_tank_combos": "pony",
    "coil_buggy_cars": "pony",
    "coil_cars_covered": "pony",
    "coil_cars_covered_asymmetric": "pony",
    "coil_cars_tarpaulin": "pony",
    "coil_cars_uncovered": "pony",
    "mineral_covered_hopper_combos": "pony",
    "covered_hopper_cars_randomised": "pony",
    "covered_hopper_cars_type_1": "pony",
    "covered_hopper_cars_type_2": "pony",
    "covered_hopper_cars_type_3": "pony",
    "cryo_tank_cars": "pony",
    "curtain_side_box_cars_randomised": "pony",
    "curtain_side_box_cars_type_1": "pony",
    "curtain_side_box_cars_type_2": "pony",
    "dedicated_coil_cars_randomised": "pony",
    "double_deck_automobile_cars": "pony",
    "double_deck_enclosed_automobile_cars": "pony",
    "drop_end_flat_cars": "pony",
    "drop_side_flat_cars": "pony",
    "mineral_open_cars": "pony",
    "mineral_open_cars_high_side": "pony",
    "mineral_open_cars_low_side": "pony",
    "mineral_open_cars_randomised": "pony",
    "express_cars_type_1": "pony",
    "express_cars_type_2": "pony",
    "express_cars_randomised": "pony",
    "express_intermodal_cars": "pony",
    "express_railcar_mail_trailer_cars": "pony",
    "express_railcar_passenger_trailer_cars": "pony",
    "farm_product_box_cars_randomised": "pony",
    "farm_product_box_cars_type_1": "pony",
    "farm_product_box_cars_type_2": "pony",
    "farm_cargo_hopper_combos": "pony",
    "farm_cargo_mixed_combos": "pony",
    "farm_product_hopper_cars_randomised": "pony",
    "farm_product_hopper_cars_type_1": "pony",
    "farm_product_hopper_cars_type_2": "pony",
    "flat_cars": "pony",
    "flat_cars_randomised": "pony",
    "flatbed_cargo_combos": "pony",
    "food_express_tank_cars_type_1": "pony",
    "food_express_tank_cars_type_2": "pony",
    "food_express_tank_cars_randomised": "pony",
    "food_hopper_cars_type_1": "pony",
    "food_hopper_cars_type_2": "pony",
    "food_hopper_cars_type_3": "pony",
    "food_express_box_combos": "pony",
    "food_express_liquid_combos": "pony",
    "food_ingredients_hopper_combos": "pony",
    "food_ingredients_mixed_combos": "pony",
    "heavy_duty_dump_cars": "pony",
    "heavy_duty_flat_cars": "pony",
    "high_end_bolster_cars": "pony",
    "bolster_cars_randomised": "pony",
    "high_speed_mail_cars": "pony",
    "high_speed_passenger_cars": "pony",
    "hood_open_cars_type_1": "pony",
    "bulk_cargo_hopper_combos": "pony",
    "hopper_cars": "pony",
    "hopper_cars_high_side": "pony",
    "hopper_cars_randomised": "pony",
    "ingot_cars": "pony",
    "intermodal_cars": "pony",
    "kaolin_hopper_cars": "pony",
    "lime_covered_hopper_cars_randomised": "pony",
    "lime_covered_hopper_cars_type_1": "pony",
    "lime_covered_hopper_cars_type_2": "pony",
    "lime_covered_hopper_cars_type_3": "pony",
    "livestock_cars": "pony",
    "livestock_express_cars": "pony",
    "log_cars": "pony",
    "low_floor_intermodal_cars": "pony",
    "low_floor_automobile_cars": "pony",
    "mail_cars": "pony",
    "merchandise_box_cars": "pony",
    "metal_product_covered_combos": "pony",
    "metal_product_mixed_combos": "pony",
    "metal_product_uncovered_combos": "pony",
    "mgr_hopper_cars": "pony",
    "mgr_hopper_top_hood_cars": "pony",
    "mill_flat_cars_randomised": "pony",
    "mill_flat_cars_type_1": "pony",
    "mill_flat_cars_type_2": "pony",
    "mill_open_cars_randomised": "pony",
    "mill_open_cars_type_1": "pony",
    "mill_open_cars_type_2": "pony",
    "motorail_automobile_cars": "pony",
    "open_car_combos": "pony",
    "open_cars_type_1": "pony",
    "open_cars_type_2": "pony",
    "open_cars_type_3": "pony",
    "open_cars_randomised": "pony",
    "panoramic_cars": "pony",
    "passenger_cars": "pony",
    "peat_cars": "pony",
    "piece_goods_covered_combos": "pony",
    "piece_goods_manufacturing_parts_combos": "pony",
    "piece_goods_mixed_combos": "pony",
    "piece_goods_easiloader_combos": "pony",
    "pipe_cars": "pony",
    "pressure_tank_cars": "pony",
    "product_tank_cars_randomised": "pony",
    "product_tank_cars_type_1": "pony",
    "product_tank_cars_type_2": "pony",
    "railbus_passenger_trailer_cars": "pony",
    "railcar_passenger_trailer_cars": "pony",
    "reefer_cars_randomised": "pony",
    "reefer_cars_type_1": "pony",
    "reefer_cars_type_2": "pony",
    "restaurant_cars": "pony",
    "rock_hopper_cars": "pony",
    "roller_roof_hopper_cars_randomised": "pony",
    "roller_roof_hopper_cars_type_1": "pony",
    "roller_roof_hopper_cars_type_2": "pony",
    "scrap_metal_cars_type_1": "pony",
    "scrap_metal_cars_type_2": "pony",
    "scrap_metal_cars_randomised": "pony",
    "side_door_hopper_cars": "pony",
    "silo_cars_randomised": "pony",
    "silo_cars_type_1": "pony",
    "silo_cars_type_2": "pony",
    "silo_cars_type_3": "pony",
    "skip_cars": "pony",
    "slag_ladle_cars": "pony",
    "sliding_roof_cars": "pony",
    "sliding_roof_hi_cube_cars": "pony",
    "sliding_wall_cars_randomised": "pony",
    "sliding_wall_cars_type_1": "pony",
    "sliding_wall_cars_type_2": "pony",
    "sliding_wall_cars_type_3": "pony",
    "spacer_cars_type_1": "pony",
    "spacer_cars_type_2": "pony",
    "suburban_passenger_cars": "pony",
    "swing_roof_hopper_cars": "pony",
    "tank_cars_randomised": "pony",
    "tank_cars_type_1": "pony",
    "tank_cars_type_2": "pony",
    "tarpaulin_cars_randomised": "pony",
    "tarpaulin_cars_type_1": "pony",
    "tarpaulin_cars_type_2": "pony",
    "tarpaulin_cars_type_3": "pony",
    "tippler_bulk_open_cars_randomised": "pony",
    "tippler_bulk_open_cars_type_1": "pony",
    "tippler_bulk_open_cars_type_2": "pony",
    "tippler_rotary_bulk_open_cars_type_1": "pony",
    "torpedo_cars": "pony",
    "vehicle_parts_box_cars": "pony",
    "volatiles_tank_cars_type_1": "pony",
}


def main():
    return Roster(
        id="pony",
        numeric_id=1,
        # note that the grf name is Iron Horse, as the pony roster was released for many years under that name, and changing it would needlessly confuse players
        # but to avoid overloading the word 'horse', which is widely used in src, we continue using 'pony' as the roster id
        grf_name="iron-horse",
        grfid=r"CA\12\23",
        str_grf_name="Iron Horse",
        # ELRL, ELNG is mapped to RAIL, NG etc
        # default intro dates per generation, can be over-ridden if needed by setting intro_year kw on model def
        intro_years={
            "RAIL": [1860, 1900, 1930, 1960, 1990, 2020],
            "METRO": [1900, 1950, 2000],
            "NG": [1860, 1910, 1960, 2010],
        },
        # default speeds per generation, can be over-ridden if needed by setting speed kw arg on model def
        # speeds roughly same as RH trucks of same era + 5mph or so, and a bit higher at the top end (back and forth on this many times eh?),
        # NG is Corsican-style 1000mm, native brit NG is not a thing for gameplay
        speeds={
            "RAIL": {
                # gen 5 and 6 held down by design, really fast freight is imbalanced
                "standard": [
                    45,
                    45,
                    60,
                    75,
                    87,
                    87,
                ],
                # match standard, except gen 6
                "suburban": [45, 45, 60, 75, 87, 99],
                # smaller steps in gen 5 and 6, balances against faster HSTs
                "express": [
                    60,
                    75,
                    90,
                    105,
                    120,
                    120,
                ],
                "express_on_lgv": [
                    0,
                    0,
                    0,
                    0,
                    155,  # keep aligned to TGV speed
                    155,
                ],
                "hst": [0, 0, 0, 112, 128, 128],
                "hst_on_lgv": [
                    0,
                    0,
                    0,
                    0,
                    155,
                    155,
                ],  # keep aligned to TGV speed....HST theoretical top speed on 5000 hp is about 155 mph so eh
                "very_high_speed": [0, 0, 0, 0, 128, 128],
                "very_high_speed_on_lgv": [0, 0, 0, 0, 155, 186],
            },
            "METRO": {
                "standard": [45, 55, 65]
                # only standard for metro in Pony
            },
            "NG": {
                # NG standard/suburban/express all *same* in Pony, balanced against trams, RVs
                # suburban and express have to be provided as some vehicles expect it, just copying it in is easiest solution
                "standard": [45, 45, 60, 75],
                "suburban": [45, 45, 60, 75],
                "express": [45, 45, 60, 75],
            },
        },
        # capacity factor per generation, will be multiplied by vehicle length
        freight_car_capacity_per_unit_length={
            "RAIL": [4, 4, 5, 5.5, 6, 6],
            "NG": [3, 3, 4, 4],
            "METRO": [4, 5, 6],
        },
        pax_car_capacity_per_unit_length={
            "RAIL": [3, 3.75, 4.5, 5.25, 6, 6],
            "NG": [3, 5, 5, 6],
        },
        pax_car_capacity_types={
            "default": {
                "multiplier": 1,
                "loading_speed_multiplier": 1,
            },
            "high_capacity": {
                "multiplier": 1.5,
                "loading_speed_multiplier": 1.75,
            },
            "restaurant": {
                "multiplier": 0.45,
                "loading_speed_multiplier": 1,
            },
            # very specifically tuned multiplier against combine vehicles
            "autocoach_combine": {
                "multiplier": 2.7,
                "loading_speed_multiplier": 1.75,
            },
            # very specifically tuned multiplier against combine vehicles
            "railbus_combine": {
                "multiplier": 2.5,
                "loading_speed_multiplier": 1.75,
            },
            "railbus_combine_ng_1": {
                "multiplier": 2,
                "loading_speed_multiplier": 1.5,
            },
            "railbus_combine_ng_2": {
                "multiplier": 1.5,
                "loading_speed_multiplier": 1.25,
            },
        },
        # freight car weight factor varies slightly by gen, reflecting modern cars with lighter weight
        train_car_weight_factors=[0.5, 0.5, 0.5, 0.48, 0.44, 0.40],
        # specify lists of cc2 colours, and an option to remap all the cc1 to a specific other cc (allowing multiple input colours to map to one result)
        # generally, reuse of these is encouraged, they're (mostly) just metadata and can be repeated multiple times for different spriterows of a vehicle
        # keep alphabetised
        engine_and_misc_car_liveries={
            "BANGER_BLUE": {
                "remap_to_cc": None,
                "docs_image_input_cc": [
                    ("COLOUR_RED", "COLOUR_WHITE"),
                    ("COLOUR_DARK_BLUE", "COLOUR_WHITE"),
                    ("COLOUR_PALE_GREEN", "COLOUR_ORANGE"),
                ],
            },
            "CLASSIC_LINES": {
                "remap_to_cc": None,
                "docs_image_input_cc": [
                    ("COLOUR_RED", "COLOUR_WHITE"),
                    ("COLOUR_DARK_BLUE", "COLOUR_WHITE"),
                    ("COLOUR_PALE_GREEN", "COLOUR_ORANGE"),
                ],
            },
            "DUTCH": {
                "remap_to_cc": {
                    "company_colour1": "COLOUR_GREY",
                    "company_colour2": "company_colour1",
                },
                "proxy_livery_for_badge_display_and_filter": "SLABSIDE",
                "docs_image_input_cc": [
                    ("COLOUR_RED", "COLOUR_WHITE"),
                    ("COLOUR_YELLOW", "COLOUR_WHITE"),
                    ("COLOUR_GREY", "COLOUR_WHITE"),
                    ("COLOUR_PALE_GREEN", "COLOUR_ORANGE"),
                ],
            },
            "FARMFLOW": {
                "remap_to_cc": None,
                "docs_image_input_cc": [
                    ("COLOUR_RED", "COLOUR_WHITE"),
                ],
            },
            "FREIGHT_BLACK": {
                "remap_to_cc": None,
                "docs_image_input_cc": [
                    ("COLOUR_RED", "COLOUR_WHITE"),
                    ("COLOUR_DARK_BLUE", "COLOUR_WHITE"),
                    ("COLOUR_PALE_GREEN", "COLOUR_ORANGE"),
                ],
            },
            "FREIGHTLINER_GBRF": {
                # note the remap to yellow, allowing 1cc wagons to be whatever player chooses
                "remap_to_cc": {
                    "company_colour1": "COLOUR_YELLOW",
                    "company_colour2": "company_colour1",
                },
                "proxy_livery_for_badge_display_and_filter": "SUPERGRAPHIC",
                "docs_image_input_cc": [
                    ("COLOUR_RED", "COLOUR_WHITE"),
                    ("COLOUR_MAUVE", "COLOUR_YELLOW"),
                    ("COLOUR_PALE_GREEN", "COLOUR_ORANGE"),
                ],
            },
            "INDUSTRIAL_YELLOW": {
                "remap_to_cc": {
                    "company_colour1": "COLOUR_YELLOW",
                    "company_colour2": "company_colour2",
                },
                "docs_image_input_cc": [
                    ("COLOUR_RED", "COLOUR_WHITE"),
                ],
            },
            "INTERCITY_RASPBERRY_RIPPLE": {
                "remap_to_cc": None,
                "docs_image_input_cc": [
                    ("COLOUR_RED", "COLOUR_WHITE"),
                    ("COLOUR_LIGHT_BLUE", "COLOUR_WHITE"),
                    ("COLOUR_PALE_GREEN", "COLOUR_ORANGE"),
                ],
            },
            "METROLAND": {
                "remap_to_cc": None,
                "docs_image_input_cc": [
                    ("COLOUR_RED", "COLOUR_WHITE"),
                    ("COLOUR_DARK_BLUE", "COLOUR_WHITE"),
                    ("COLOUR_PALE_GREEN", "COLOUR_ORANGE"),
                ],
            },
            "RAILFREIGHT_RED_STRIPE": {
                "remap_to_cc": {
                    "company_colour1": "COLOUR_GREY",
                    "company_colour2": "company_colour1",
                },
                "proxy_livery_for_badge_display_and_filter": "SUPERGRAPHIC",
                "docs_image_input_cc": [
                    ("COLOUR_RED", "COLOUR_WHITE"),
                    ("COLOUR_PINK", "COLOUR_WHITE"),
                    ("COLOUR_PALE_GREEN", "COLOUR_ORANGE"),
                ],
            },
            "RAILFREIGHT_TRIPLE_GREY": {
                # note the remap to white, to provide lightest of the triple greys as cc1
                "remap_to_cc": {
                    "company_colour1": "COLOUR_WHITE",
                    "company_colour2": "company_colour1",
                },
                "proxy_livery_for_badge_display_and_filter": "SUPERGRAPHIC",
                "docs_image_input_cc": [
                    ("COLOUR_RED", "COLOUR_WHITE"),
                    ("COLOUR_DARK_BLUE", "COLOUR_WHITE"),
                    ("COLOUR_PALE_GREEN", "COLOUR_ORANGE"),
                ],
            },
            "RIDEWELL": {
                "remap_to_cc": None,
                "docs_image_input_cc": [
                    ("COLOUR_RED", "COLOUR_WHITE"),
                    ("COLOUR_DARK_BLUE", "COLOUR_WHITE"),
                    ("COLOUR_PALE_GREEN", "COLOUR_ORANGE"),
                ],
            },
            "ROYAL_MAIL_RES": {
                "remap_to_cc": None,
                "docs_image_input_cc": [
                    ("COLOUR_RED", "COLOUR_WHITE"),
                    ("COLOUR_RED", "COLOUR_LIGHT_BLUE"),
                    ("COLOUR_PALE_GREEN", "COLOUR_ORANGE"),
                ],
            },
            "ROYAL_MAIL_RES": {
                "remap_to_cc": {
                    "company_colour1": "COLOUR_RED",
                    "company_colour2": "company_colour2",
                },
                "docs_image_input_cc": [
                    ("COLOUR_RED", "COLOUR_WHITE"),
                ],
            },
            "SHOW_PONY": {
                "remap_to_cc": None,
                "docs_image_input_cc": [
                    ("COLOUR_RED", "COLOUR_WHITE"),
                    ("COLOUR_DARK_BLUE", "COLOUR_WHITE"),
                    ("COLOUR_PALE_GREEN", "COLOUR_ORANGE"),
                ],
            },
            "SLABSIDE": {
                "remap_to_cc": None,
                "docs_image_input_cc": [
                    ("COLOUR_RED", "COLOUR_WHITE"),
                    ("COLOUR_DARK_BLUE", "COLOUR_WHITE"),
                    ("COLOUR_PALE_GREEN", "COLOUR_ORANGE"),
                ],
            },
            "STOCK_STANDARD": {
                "remap_to_cc": None,
                "docs_image_input_cc": [
                    ("COLOUR_RED", "COLOUR_WHITE"),
                    ("COLOUR_DARK_BLUE", "COLOUR_WHITE"),
                    ("COLOUR_PALE_GREEN", "COLOUR_ORANGE"),
                ],
            },
            "SUPERGRAPHIC": {
                "remap_to_cc": None,
                "docs_image_input_cc": [
                    ("COLOUR_RED", "COLOUR_WHITE"),
                    ("COLOUR_DARK_BLUE", "COLOUR_WHITE"),
                    ("COLOUR_PALE_GREEN", "COLOUR_ORANGE"),
                ],
            },
            "SURE_PACE": {
                "remap_to_cc": None,
                "docs_image_input_cc": [
                    ("COLOUR_RED", "COLOUR_WHITE"),
                    ("COLOUR_DARK_BLUE", "COLOUR_WHITE"),
                    ("COLOUR_PALE_GREEN", "COLOUR_ORANGE"),
                ],
            },
            "SWOOSH": {
                "remap_to_cc": None,
                "docs_image_input_cc": [
                    ("COLOUR_RED", "COLOUR_WHITE"),
                    ("COLOUR_DARK_BLUE", "COLOUR_WHITE"),
                    ("COLOUR_PALE_GREEN", "COLOUR_ORANGE"),
                ],
            },
            # the default "nothing" livery
            "VANILLA": {
                "remap_to_cc": None,
                "docs_image_input_cc": [
                    ("COLOUR_RED", "COLOUR_WHITE"),
                    ("COLOUR_DARK_BLUE", "COLOUR_WHITE"),
                    ("COLOUR_PALE_GREEN", "COLOUR_ORANGE"),
                ],
            },
            "WORKHORSE": {
                "remap_to_cc": None,
                "docs_image_input_cc": [
                    ("COLOUR_RED", "COLOUR_WHITE"),
                    ("COLOUR_DARK_BLUE", "COLOUR_WHITE"),
                    ("COLOUR_PALE_GREEN", "COLOUR_ORANGE"),
                ],
            },
        },
        # lists of 2-tuple (livery_name, relative_spriterow_num) for pax / mail vehicles
        # buy menu order will match list order
        # - livery name comes from roster engine_and_misc_car_liveries
        # - relative_spriterow_num allows reordering sprites relative to spritesheet
        pax_mail_livery_groups={
            "default_pax_liveries": [("SURE_PACE", 0), ("RIDEWELL", 1)],
            "gen_2_pax_liveries": [("RIDEWELL", 0), ("SURE_PACE", 1)],
            "gen_5_and_6_pax_liveries": [
                ("INTERCITY_RASPBERRY_RIPPLE", 0),
                ("CLASSIC_LINES", 1),
                ("VANILLA", 2),
                ("VANILLA", 3),
            ],
            "CABBAGE_RAILCAR": [
                ("VANILLA", 1),
                ("VANILLA", 0),
            ],
            "default_suburban_pax_liveries": [
                ("RIDEWELL", 1),
                ("SURE_PACE", 0),
            ],
            "gen_2_suburban_pax_liveries": [
                ("SURE_PACE", 1),
                ("RIDEWELL", 0),
            ],
            "default_mail_liveries": [
                ("ROYAL_MAIL_RES", 3),
                ("SURE_PACE", 0),
                ("RIDEWELL", 1),
                ("BANGER_BLUE", 2),
                ("ROYAL_MAIL_RES", 4),
            ],
            "gen_2_mail_liveries": [
                ("ROYAL_MAIL_RES", 3),
                ("RIDEWELL", 1),
                ("SURE_PACE", 0),
                ("BANGER_BLUE", 2),
                ("ROYAL_MAIL_RES", 4),
            ],
            "gen_5_and_6_mail_liveries": [
                ("VANILLA", 5),
                ("INTERCITY_RASPBERRY_RIPPLE", 0),
                ("CLASSIC_LINES", 1),
                ("VANILLA", 2),
                ("VANILLA", 3),
                ("ROYAL_MAIL_RES", 4),
                ("ROYAL_MAIL_RES", 6),
            ],
            "diesel_railcar_mail_liveries": [
                ("ROYAL_MAIL_RES", 2),
                ("INTERCITY_RASPBERRY_RIPPLE", 0),
                ("VANILLA", 1),
                ("VANILLA", 3),
                ("ROYAL_MAIL_RES", 4),
            ],
            "electric_railcar_mail_liveries": [
                ("VANILLA", 3),
                ("INTERCITY_RASPBERRY_RIPPLE", 0),
                ("VANILLA", 1),
                ("ROYAL_MAIL_RES", 2),
                ("ROYAL_MAIL_RES", 4),
            ],
            "dvt_mail_liveries": [
                ("VANILLA", 0),
                ("VANILLA", 1),
                ("VANILLA", 2),
                ("VANILLA", 3),
            ],
            "metro_pax_liveries": [
                ("METROLAND", 0),
                ("METROLAND", 1),
            ],
            "metro_mail_liveries": [
                ("METROLAND", 0),
                ("METROLAND", 1),
                ("ROYAL_MAIL_RES", 2),
            ],
            "default_motorail_liveries": [("VANILLA", 0), ("VANILLA", 1), ("STOCK_STANDARD", 2)],
            "gen_5_and_6_motorail_liveries": [("INTERCITY_RASPBERRY_RIPPLE", 0), ("CLASSIC_LINES", 1), ("VANILLA", 2)],
        },
        engine_module_names=engine_module_names,
        wagon_module_names_with_roster_ids=wagon_module_names_with_roster_ids,
    )
