import importlib

from spritelayer_cargos import registered_spritelayer_cargos # CABBAGE
from gestalt_graphics import pipelines


class SpritelayerCargo(object):
    """Simple generic class for spritelayer cargos"""

    base_id = None  # set by subclass

    def __init__(self, **kwargs):
        # assume cargo sprites are symmetric by default, over-ride in subclasses as needed
        self.cargo_sprites_are_asymmetric = False
        self.platform_type = kwargs.get("platform_type")
        self.length = kwargs.get("length")
        self.cargo_sets = []
        # assume platform vehicle is symmetric by default, only one reverse state needed
        self.supported_reverse_states = ["unreversed"]
        # option to fill in gaps in container shadows
        self.provide_container_shadows = kwargs.get("provide_container_shadows", False)
        self.pipelines = pipelines.get_pipelines(["generate_spritelayer_cargo_sets"])

    @property
    def id(self):
        return self.base_id + "_" + self.platform_type + "_" + str(self.length) + "px"

    @property
    def cargo_label_mapping(self):
        # convenience wrapper so we can access the class method as a property for consistency with similar access elsewhere
        return self.get_cargo_label_mapping()

    @property
    def floor_height_for_platform_type(self):
        # crude resolution of floor height for each platform type
        return self.all_platform_types_with_floor_heights[self.platform_type]

    def desync_decks(self, cargo_set, repeat_index):
        # option to force variation between cargos for upper and lower deck layers on double-deck vehicles
        # this is a crude hack on the template ordering for a random switch, there's no deeper architecture
        if self.platform_type in ["double_deck_upper"]:
            # just a crude reversal of order
            return len(cargo_set.variants) - 1 - repeat_index
        return repeat_index

    def render(self, templates, graphics_path):
        # templating
        template_name = "spritelayer_cargo.pynml"
        template = templates[template_name]
        nml_result = template(
            graphics_path=graphics_path,
            spritelayer_cargo=self,
        )
        return nml_result


class CargoSetBase(object):
    # provides sets of cargo sprites of specific appearance e.g. tank container, flatrack container etc
    # each set corresponds to a spritesheet which will be generated by the graphics processor
    # each set is used for a specific group of cargo labels or classes
    # each set may have one or more spriterows
    # spriterows are chosen randomly when vehicles load new cargo
    # rows are composed by the graphics processor, and may include variations for
    # - combinations of cargo lengths
    # - combinations of cargo types
    # - cargo colours
    def __init__(self, **kwargs):
        self.subtype = kwargs.get("subtype")
        self.subtype_suffix = kwargs.get("subtype_suffix")
        # self.spritelayer_cargo = kwargs.get("spritelayer_cargo")
        # CABBAGE - horrific autoregistration on init UGH
        print("oof - self registering inits :|", kwargs.get("spritelayer_cargo_type"), self.subtype)
        self.register_cargo_set(kwargs.get("spritelayer_cargo_type"))


    def register_cargo_set(self, spritelayer_cargo_type):
        for platform_type in self.compatible_platform_types:
            spritelayer_cargo = spritelayer_cargo_type(
                platform_type=platform_type,
                length=self.length,
            )
            # the spritelayer_cargo may already be registered, this is a valid side effect of the implementation
            # but we don't want to register the same spritelayer_cargo multiple times (waste of compile time and can cause bugs with multiprocessing)
            already_registered = False
            for registered_spritelayer_cargo in registered_spritelayer_cargos:
                if registered_spritelayer_cargo.id == spritelayer_cargo.id:
                    already_registered = True
                    spritelayer_cargo = registered_spritelayer_cargo
                    break
            if already_registered == False:
                registered_spritelayer_cargos.append(spritelayer_cargo)
            spritelayer_cargo.cargo_sets.append(self)

    def id(self, spritelayer_cargo):
        return (
            spritelayer_cargo.base_id
            + "_"
            + spritelayer_cargo.platform_type
            + "_"
            + self.subtype
            + "_"
            + self.subtype_suffix
            + "_"
            + str(spritelayer_cargo.length)
            + "px"
        )


class SpritelayerCargoManager(list):
    """
    It's convenient to have a structure for working with spritelayer_cargos.
    This is a class to manage that, intended for use as a singleton, which can be passed to templates etc.
    Extends default python list, as it's a convenient behaviour (the instantiated class instance behaves like a list object).
    """

    def __init__(self, registered_spritelayer_cargos):
        # init not needed, just shim
        self.registered_spritelayer_cargos = registered_spritelayer_cargos #

    def add_spritelayer_cargos(self, spritelayer_cargo_module_names):
        for spritelayer_cargo_module_name in spritelayer_cargo_module_names:
            spritelayer_cargo_module = importlib.import_module(
                "." + spritelayer_cargo_module_name, package="spritelayer_cargos"
            )
            spritelayer_cargo_module.main(self)

    def register_cargo_set(self, spritelayer_cargo_set_type, spritelayer_cargo_type, subtype, subtype_suffix):
        print("register_cargo_set_type")
        cargo_set = spritelayer_cargo_set_type(
            subtype=subtype,
            subtype_suffix=subtype_suffix,
            spritelayer_cargo_type=spritelayer_cargo_type,
        )
        print(cargo_set)


    """
    def add_spritelayer_cargos(self, spritelayer_cargo_module_names):
        for spritelayer_cargo_module_name in spritelayer_cargo_module_names:
            spritelayer_cargo_module = importlib.import_module(
                "." + spritelayer_cargo_module_name, package="spritelayer_cargos"
            )
            spritelayer_cargo = spritelayer_cargo_module.main(disabled=False)
            self.append(spritelayer_cargo)

    def get_spritelayer_cargo_by_vehicle_track_type_name(self, vehicle_track_type_name):
        for spritelayer_cargo in self:
            if spritelayer_cargo.vehicle_track_type_name == vehicle_track_type_name:
                return spritelayer_cargo
        raise ValueError(
            f"No spritelayer_cargo found with vehicle_track_type_name={vehicle_track_type_name}"
        )
    """
