#from roster import Roster
# import rosters
#from rosters import registered_rosters

from rosters import pony
pony.roster.register(disabled=False)

#from vehicles import box_cars
#box_cars.main()

"""
from vehicles import ares
from vehicles import athena
from vehicles import bean_feast
from vehicles import blackthorn
from vehicles import blaze
from vehicles import boar_cat
from vehicles import braf
from vehicles import breeze
from vehicles import brenner_cab
from vehicles import brenner_middle
from vehicles import carrack
from vehicles import cheddar_valley
from vehicles import cheese_bug
from vehicles import chimera
from vehicles import chinook
from vehicles import deasil
from vehicles import dover
from vehicles import dragon
from vehicles import driving_cab_pony_gen_5
from vehicles import driving_cab_pony_gen_6
from vehicles import fleet
from vehicles import flanders_storm
from vehicles import flindermouse
from vehicles import fury
from vehicles import geronimo
from vehicles import girt_licker
from vehicles import goliath
from vehicles import gosling_blast
from vehicles import gowsty
from vehicles import grid
from vehicles import griffon
from vehicles import gronk
from vehicles import growler
from vehicles import grub
from vehicles import gwynt
from vehicles import haar
from vehicles import happy_train
from vehicles import helm_wind_cab
from vehicles import helm_wind_middle
from vehicles import hercules
from vehicles import hurly_burly
from vehicles import jupiter
from vehicles import kelpie
from vehicles import lark
from vehicles import lemon
from vehicles import little_bear
from vehicles import longwater
from vehicles import mail_rail
from vehicles import merrylegs
from vehicles import moor_gallop
from vehicles import mumble
from vehicles import peasweep
from vehicles import pegasus
from vehicles import phoenix
from vehicles import pikel
from vehicles import pinhorse
from vehicles import plastic_postbox
from vehicles import proper_job
from vehicles import pylon
from vehicles import revolution
from vehicles import roarer
from vehicles import saxon
from vehicles import scooby
from vehicles import scorcher
from vehicles import screamer
from vehicles import serpentine
from vehicles import shoebox
from vehicles import shredder
from vehicles import sizzler
from vehicles import slammer
from vehicles import slug
from vehicles import snapper
from vehicles import snowplough_pony_gen_2
from vehicles import spinner
from vehicles import stoat
from vehicles import super_shoebox
from vehicles import tencendur
from vehicles import thunderbird
from vehicles import tideway
from vehicles import tin_rocket
from vehicles import tyburn
from vehicles import ultra_shoebox
from vehicles import upcountry
from vehicles import westbourne
from vehicles import workish
from vehicles import wyvern
from vehicles import zeus
from vehicles import zorro
"""
